# Generated by C++ Compiler - Code Generation Phase
# x86-64 Assembly Output for Windows (MinGW64)

.text
.globl main

main:
    # Program start
    pushq %rbp
    movq %rsp, %rbp
    subq $32, %rsp
    movq $42, %r8
    # Load integer literal: 42
    movq %r8, %rax
    # Program exit
    addq $32, %rsp
    movq %rbp, %rsp
    popq %rbp
    ret
