# Generated by C++ Compiler - Code Generation Phase
# x86-64 Assembly Output for Windows (MinGW64)

.text
.globl main

main:
    # Program start
    pushq %rbp
    movq %rsp, %rbp
    subq $32, %rsp
    movq $2, %r8
    # Load integer literal: 2
    movq $3, %r9
    # Load integer literal: 3
    movq $4, %r10
    # Load integer literal: 4
    # Binary operation: %r9 * %r10
    imulq %r10, %r9
    # Binary operation: %r8 + %r9
    addq %r9, %r8
    movq %r8, %rax
    # Program exit
    addq $32, %rsp
    movq %rbp, %rsp
    popq %rbp
    ret
