# Generated by C++ Compiler - Code Generation Phase
# x86-64 Assembly Output

.section .text
.global _start

_start:
    # Program start
    movq $2, %r8
    # Load integer literal: 2
    movq $3, %r9
    # Load integer literal: 3
    movq $4, %r10
    # Load integer literal: 4
    # Binary operation: %r9 * %r10
    imulq %r10, %r9
    # Binary operation: %r8 + %r9
    addq %r9, %r8
    # Program exit
    movq $0, %rdi
    movq $60, %rax
    syscall
