# Generated by C++ Compiler - Code Generation Phase
# x86-64 Assembly Output for Windows (MinGW64)

.text
.globl main

main:
    # Program start
    pushq %rbp
    movq %rsp, %rbp
    subq $32, %rsp
    # Variable 'a' allocated at offset -8
    movq $5, %r8
    # Load integer literal: 5
    movq %r8, -8(%rbp)
    # Store to variable 'a'
    movq -8(%rbp), %r8
    # Load variable 'a'
    movq $3, %r9
    # Load integer literal: 3
    # Binary operation: %r8 + %r9
    addq %r9, %r8
    movq %r8, %rax
    # Program exit
    addq $32, %rsp
    movq %rbp, %rsp
    popq %rbp
    ret
